package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// OllamaProvider implements the Provider interface for Ollama local AI
type OllamaProvider struct {
	endpoint string // e.g., "http://localhost:11434"
	model    string // e.g., "codellama:7b", "llama3:8b", "mistral:7b"
	client   *http.Client
}

// OllamaGenerateRequest represents the request format for Ollama API
type OllamaGenerateRequest struct {
	Model  string `json:"model"`
	Prompt string `json:"prompt"`
	Stream bool   `json:"stream"`
}

// OllamaGenerateResponse represents the response format from Ollama API
type OllamaGenerateResponse struct {
	Model         string `json:"model"`
	Response      string `json:"response"`
	Done          bool   `json:"done"`
	Context       []int  `json:"context,omitempty"`
	TotalDuration int64  `json:"total_duration,omitempty"`
	Error         string `json:"error,omitempty"`
}

// OllamaListResponse represents the response for listing models
type OllamaListResponse struct {
	Models []OllamaModel `json:"models"`
}

// OllamaModel represents a model in Ollama
type OllamaModel struct {
	Name       string `json:"name"`
	ModifiedAt string `json:"modified_at"`
	Size       int64  `json:"size"`
}

// NewOllamaProvider creates a new Ollama provider
func NewOllamaProvider(endpoint, model string) *OllamaProvider {
	if endpoint == "" {
		endpoint = "http://localhost:11434" // default Ollama endpoint
	}
	if model == "" {
		model = "codellama:7b" // default model
	}
	return &OllamaProvider{
		endpoint: endpoint,
		model:    model,
		client:   &http.Client{},
	}
}

// Name returns the provider name
func (p *OllamaProvider) Name() string {
	return "ollama"
}

// ValidateConfig validates the Ollama configuration
func (p *OllamaProvider) ValidateConfig() error {
	if p.endpoint == "" {
		return fmt.Errorf("Ollama endpoint is required")
	}
	if p.model == "" {
		return fmt.Errorf("Ollama model is required")
	}

	// Try to ping the Ollama server
	resp, err := p.client.Get(p.endpoint)
	if err != nil {
		return fmt.Errorf("failed to connect to Ollama at %s: %v. Is Ollama running?", p.endpoint, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("Ollama server returned status %d. Is Ollama running at %s?", resp.StatusCode, p.endpoint)
	}

	return nil
}

// GenerateMessages generates commit messages using Ollama API
func (p *OllamaProvider) GenerateMessages(ctx context.Context, req *GenerateRequest) (*GenerateResponse, error) {
	// Get the appropriate prompt template
	promptTemplate := GetPromptTemplate(req.Detailed, req.UseIcons)
	prompt := fmt.Sprintf(promptTemplate, req.Diff, req.LastCommit)

	// Create request body
	requestBody := OllamaGenerateRequest{
		Model:  p.model,
		Prompt: prompt,
		Stream: false, // We want a single response
	}

	jsonData, err := json.Marshal(requestBody)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %v", err)
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "POST", p.endpoint+"/api/generate", bytes.NewBuffer(jsonData))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", "application/json")

	// Send request
	resp, err := p.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to send request to Ollama: %v. Is Ollama running?", err)
	}
	defer resp.Body.Close()

	// Read response body
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	// Check for non-200 status codes
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("Ollama API request failed with status %d: %s", resp.StatusCode, string(body))
	}

	// Parse response
	var ollamaResp OllamaGenerateResponse
	if err := json.Unmarshal(body, &ollamaResp); err != nil {
		return nil, fmt.Errorf("failed to parse response: %v", err)
	}

	// Check for API errors
	if ollamaResp.Error != "" {
		return nil, fmt.Errorf("Ollama API error: %s", ollamaResp.Error)
	}

	// Extract content from response
	content := ollamaResp.Response
	if content == "" {
		return nil, fmt.Errorf("no content generated by Ollama")
	}

	// Parse the response based on mode
	messages, err := p.parseResponse(content, req.Detailed, req.UseIcons)
	if err != nil {
		return nil, fmt.Errorf("failed to parse Ollama response: %v", err)
	}

	return &GenerateResponse{
		Messages: messages,
		Provider: p.Name(),
	}, nil
}

// parseResponse parses the AI response into commit messages
// This method follows the same logic as GeminiProvider and OpenRouterProvider for consistency
func (p *OllamaProvider) parseResponse(text string, detailed, useIcons bool) ([]string, error) {
	cleanText := strings.TrimSpace(text)
	var finalMessages []string

	if detailed && !useIcons {
		// Parse detailed format (plain text with --- separators) for non-icon mode only
		finalMessages = p.parseDetailedResponse(cleanText)
	} else if detailed && useIcons {
		// Parse JSON format for detailed icon mode - messages contain newlines for body
		finalMessages = p.parseJSONResponse(cleanText)
	} else {
		// Parse JSON format for regular mode (with or without icons)
		finalMessages = p.parseJSONResponse(cleanText)
	}

	if len(finalMessages) == 0 {
		return nil, fmt.Errorf("no valid commit messages found in response: %s", cleanText)
	}

	// Ensure we have at least 3 messages
	for len(finalMessages) < 3 {
		// If we don't have enough messages, duplicate the last one with slight variation
		lastMsg := finalMessages[len(finalMessages)-1]
		finalMessages = append(finalMessages, lastMsg)
	}

	// Take only the first 3 messages
	if len(finalMessages) > 3 {
		finalMessages = finalMessages[:3]
	}

	return finalMessages, nil
}

// parseDetailedResponse parses detailed format responses (plain text with --- separators)
func (p *OllamaProvider) parseDetailedResponse(cleanText string) []string {
	var finalMessages []string

	// Split by --- separators and extract commit messages
	parts := strings.Split(cleanText, "---")
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part != "" {
			finalMessages = append(finalMessages, part)
		}
	}

	// If we don't have 3 messages from --- separator, try alternative parsing
	if len(finalMessages) < 3 {
		// Look for commit messages that start with type prefixes (with or without emoji)
		lines := strings.Split(cleanText, "\n")
		var currentMessage strings.Builder
		messages := []string{}

		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line == "" {
				// Empty line might separate commit messages or be part of body
				if currentMessage.Len() > 0 {
					currentMessage.WriteString("\n")
				}
				continue
			}

			// Check if line starts with a commit type (with or without emoji)
			if p.isCommitMessageStart(line) {
				// If we have a previous message, save it
				if currentMessage.Len() > 0 {
					messages = append(messages, strings.TrimSpace(currentMessage.String()))
					currentMessage.Reset()
				}
				// Start new message
				currentMessage.WriteString(line)
			} else if currentMessage.Len() > 0 {
				// Add to current message body
				currentStr := currentMessage.String()
				if !strings.HasSuffix(currentStr, "\n") {
					currentMessage.WriteString("\n")
				}
				currentMessage.WriteString(line)
			}
		}

		// Add the last message if any
		if currentMessage.Len() > 0 {
			messages = append(messages, strings.TrimSpace(currentMessage.String()))
		}

		if len(messages) >= 3 {
			finalMessages = messages[:3]
		} else if len(messages) > 0 {
			finalMessages = messages
		}
	}

	return finalMessages
}

// isCommitMessageStart checks if a line starts with a commit type (with or without emoji)
func (p *OllamaProvider) isCommitMessageStart(line string) bool {
	// Remove emoji if present to check for commit type
	lineWithoutEmoji := line

	// Check for emoji by looking for common commit emojis or any emoji-like character
	runes := []rune(line)
	if len(runes) > 0 && runes[0] > 127 {
		// Skip emoji and any following spaces
		i := 1
		for i < len(runes) && (runes[i] == ' ' || runes[i] > 127) {
			i++
		}
		if i < len(runes) {
			lineWithoutEmoji = string(runes[i:])
		}
	}

	// Check for standard commit types (with or without scope)
	types := []string{
		"feat:", "fix:", "docs:", "style:", "refactor:", "perf:", "test:", "chore:",
		"build:", "ci:", "revert:", "try:", "init:",
		"feat(", "fix(", "docs(", "style(", "refactor(", "perf(", "test(", "chore(",
		"build(", "ci(", "revert(", "try(", "init(",
	}

	for _, t := range types {
		if strings.HasPrefix(lineWithoutEmoji, t) {
			return true
		}
	}

	return false
}

// parseJSONResponse parses JSON format responses
func (p *OllamaProvider) parseJSONResponse(cleanText string) []string {
	// First try to extract messages from plain text format (fallback for non-compliant models)
	if strings.Contains(cleanText, "```") && !strings.Contains(cleanText, "{") {
		// Model returned plain text in code blocks instead of JSON
		messages := p.parseTextCodeBlock(cleanText)
		if len(messages) > 0 {
			return messages
		}
	}

	// Try to extract JSON from markdown code blocks
	if strings.Contains(cleanText, "```json") {
		// Extract JSON from json code block
		start := strings.Index(cleanText, "```json")
		if start != -1 {
			start += 7 // Skip "```json"
			// Skip any whitespace/newlines after ```json
			for start < len(cleanText) && (cleanText[start] == '\n' || cleanText[start] == '\r' || cleanText[start] == ' ' || cleanText[start] == '\t') {
				start++
			}
			end := strings.Index(cleanText[start:], "```")
			if end != -1 {
				cleanText = strings.TrimSpace(cleanText[start : start+end])
			}
		}
	} else if strings.Contains(cleanText, "```") {
		// Extract JSON from generic code block
		start := strings.Index(cleanText, "```")
		if start != -1 {
			start += 3 // Skip "```"
			// Skip any whitespace/newlines after ```
			for start < len(cleanText) && (cleanText[start] == '\n' || cleanText[start] == '\r' || cleanText[start] == ' ' || cleanText[start] == '\t') {
				start++
			}
			end := strings.Index(cleanText[start:], "```")
			if end != -1 {
				cleanText = strings.TrimSpace(cleanText[start : start+end])
			}
		}
	}

	// Find JSON object in the response - look for complete JSON structure
	jsonStart := strings.Index(cleanText, "{")
	if jsonStart == -1 {
		return nil
	}

	// Find the matching closing brace for the JSON object
	jsonText := ""
	braceCount := 0
	inQuotes := false
	escapeNext := false

	for i := jsonStart; i < len(cleanText); i++ {
		char := cleanText[i]

		if escapeNext {
			escapeNext = false
			continue
		}

		if char == '\\' && inQuotes {
			escapeNext = true
			continue
		}

		if char == '"' && !escapeNext {
			inQuotes = !inQuotes
		}

		if !inQuotes {
			if char == '{' {
				braceCount++
			} else if char == '}' {
				braceCount--
				if braceCount == 0 {
					jsonText = cleanText[jsonStart : i+1]
					break
				}
			}
		}
	}

	if jsonText == "" {
		return nil
	}

	// Parse JSON response
	var commitResponse CommitResponse
	if err := json.Unmarshal([]byte(jsonText), &commitResponse); err != nil {
		return nil
	}

	if len(commitResponse.Messages) == 0 {
		return nil
	}

	return commitResponse.Messages
}

// parseTextCodeBlock extracts commit messages from plain text in code blocks
// Fallback for models that don't follow JSON format instructions
func (p *OllamaProvider) parseTextCodeBlock(text string) []string {
	var messages []string

	// Extract content from code block
	start := strings.Index(text, "```")
	if start == -1 {
		return nil
	}

	start += 3 // Skip "```"
	// Skip language identifier if present
	for start < len(text) && text[start] != '\n' {
		start++
	}
	if start < len(text) {
		start++ // Skip newline
	}

	end := strings.Index(text[start:], "```")
	if end == -1 {
		return nil
	}

	content := strings.TrimSpace(text[start : start+end])
	lines := strings.Split(content, "\n")

	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		// Check if line looks like a commit message
		if p.isCommitMessageStart(line) {
			messages = append(messages, line)
		}
	}

	return messages
}

// ListModels lists all available Ollama models
func (p *OllamaProvider) ListModels(ctx context.Context) ([]OllamaModel, error) {
	httpReq, err := http.NewRequestWithContext(ctx, "GET", p.endpoint+"/api/tags", nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %v", err)
	}

	resp, err := p.client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to list models: %v. Is Ollama running?", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response: %v", err)
	}

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("failed to list models: %s", string(body))
	}

	var listResp OllamaListResponse
	if err := json.Unmarshal(body, &listResp); err != nil {
		return nil, fmt.Errorf("failed to parse response: %v", err)
	}

	return listResp.Models, nil
}
